VPP-1498: test/framework.py: AttributeError
Traceback if .send_keep_alive is called before pipe is configured.

Traceback (most recent call last):
      File "/vpp/test/test_span.py", line 27, in setUpClass
        super(TestSpan, cls).setUpClass()
      File "/vpp/test/framework.py", line 411, in setUpClass
        cls.reporter.send_keep_alive(cls, 'setUpClass')
      File "/vpp/test/framework.py", line 172, in send_keep_alive
        if self.pipe is None:
      File "/vpp/test/framework.py", line 160, in pipe
        return self._pipe
    AttributeError: 'KeepAliveReporter' object has no attribute '_pipe'

Change-Id: I561d2748441702478a84fbb4580a4d2667d70ffd
Signed-off-by: Paul Vinciguerra <pvinci@vinciconsulting.com>