Revert "VPP-1508 python3 tests: raw_input"
This reverts commit 7e44d49d7f0e4321c02bf720095c411bcae856dc.

Reason for revert: Traceback (most recent call last):
  File "/home/ksekera/vpp/test/test_ipsec_ah.py", line 36, in
setUpClass
    super(TemplateIpsecAh, cls).setUpClass()
  File "/home/ksekera/vpp/test/template_ipsec.py", line 105, in
setUpClass
    super(TemplateIpsec, cls).setUpClass()
  File "/home/ksekera/vpp/test/framework.py", line 459, in setUpClass
    cls.quit()
  File "/home/ksekera/vpp/test/framework.py", line 475, in quit
    six.input("When done debugging, press ENTER to kill the "
AttributeError: 'module' object has no attribute 'input'

Change-Id: Idf0bbfea231730b37bae5dcb4557a0f82ab1b810
Signed-off-by: Ole Troan <ot@cisco.com>